"""
Generate Cache Configuration File

This script reads the optimization results and generates a production-ready
TypeScript configuration file for the KV-cache system.

It reads the JSON results from all optimization runs and creates a
well-documented TypeScript configuration file.
"""

import json
import os
from typing import Dict, Any

def load_results() -> Dict[str, Any]:
    """Load all optimization results"""
    results_dir = "simulations/optimization/memory/results"

    results = {}

    # Load compression results
    compression_path = os.path.join(results_dir, "compression_results.json")
    if os.path.exists(compression_path):
        with open(compression_path, 'r') as f:
            results['compression'] = json.load(f)

    # Load eviction results
    eviction_path = os.path.join(results_dir, "eviction_results.json")
    if os.path.exists(eviction_path):
        with open(eviction_path, 'r') as f:
            results['eviction'] = json.load(f)

    # Load ANN results
    ann_path = os.path.join(results_dir, "ann_results.json")
    if os.path.exists(ann_path):
        with open(ann_path, 'r') as f:
            results['ann'] = json.load(f)

    # Load sizing results
    sizing_path = os.path.join(results_dir, "sizing_results.json")
    if os.path.exists(sizing_path):
        with open(sizing_path, 'r') as f:
            results['sizing'] = json.load(f)

    # Load prefetch results
    prefetch_path = os.path.join(results_dir, "prefetch_results.json")
    if os.path.exists(prefetch_path):
        with open(prefetch_path, 'r') as f:
            results['prefetch'] = json.load(f)

    return results

def extract_optimal_params(results: Dict[str, Any]) -> Dict[str, Any]:
    """Extract optimal parameters from results"""
    optimal = {}

    # Compression
    if 'compression' in results and 'optimal_configs' in results['compression']:
        optimal['compression'] = results['compression']['optimal_configs']

    # Eviction
    if 'eviction' in results and 'optimal' in results['eviction']:
        optimal['eviction'] = results['eviction']['optimal']

    # ANN
    if 'ann' in results and 'optimal' in results['ann']:
        optimal['ann'] = results['ann']['optimal']

    # Sizing
    if 'sizing' in results and 'optimal_sizes' in results['sizing']:
        optimal['sizing'] = results['sizing']['optimal_sizes']

    # Prefetch
    if 'prefetch' in results and 'optimal' in results['prefetch']:
        optimal['prefetch'] = results['prefetch']['optimal']

    return optimal

def generate_config_ts(optimal: Dict[str, Any]) -> str:
    """Generate TypeScript configuration file content"""
    content = """/**
 * KV-Cache Configuration for POLLN
 *
 * Auto-generated by: simulations/optimization/memory/generate_config.py
 * Generation Date: 2026-03-07
 *
 * This file contains optimal parameters for the KV-cache system based on
 * comprehensive simulation testing. These parameters have been validated
 * across multiple workloads and access patterns.
 *
 * Configuration Categories:
 * - compression: Compression strategies for different cache types
 * - eviction: Cache eviction policies and sizing
 * - annIndex: Approximate Nearest Neighbor index parameters
 * - prefetch: Prefetching strategy settings
 *
 * To regenerate: Run `python simulations/optimization/memory/run_all.py`
 */

import type { CompressionMethod, EvictionPolicy, ANNAlgorithm } from '../types';

/**
 * Main KV-Cache configuration object
 *
 * This configuration is optimized for production use across multiple
 * workload types: conversation, coding, analysis, and general mixed workloads.
 */
export const KV_CACHE_CONFIG = {
"""

    # Add compression config
    content += "\n  /**\n   * Compression settings for different KV-cache types\n"
    content += "   *\n"
    content += "   * Each cache type (attention, MLP, embedding, FFN) has different\n"
    content += "   * characteristics and optimal compression strategies.\n"
    content += "   */\n"
    content += "  compression: {\n"

    if 'compression' in optimal:
        for cache_type, settings in optimal['compression'].items():
            method = settings.get('method', 'svd')
            ratio = settings.get('compression_ratio', 0.1)
            quality = settings.get('quality', 0.95)

            content += f"\n    /**\n"
            content += f"     * {cache_type.upper()} cache compression\n"
            content += f"     *\n"
            content += f"     * Method: {method}\n"
            content += f"     * Compression Ratio: {ratio:.3f} ({1/ratio:.1f}x reduction)\n"
            content += f"     * Expected Quality: {quality:.3f} (cosine similarity)\n"
            content += f"     */\n"
            content += f"    {cache_type}: {{\n"
            content += f"      method: '{method}' as CompressionMethod,\n"
            content += f"      ratio: {ratio},\n"
            content += f"      quality: {quality},\n"

            # Add method-specific parameters
            params = settings.get('parameters', {})
            if params:
                content += f"      params: {json.dumps(params)},\n"

            content += f"    }},\n"

    content += "  },\n"

    # Add eviction config
    content += "\n  /**\n"
    content += "   * Eviction policy settings\n"
    content += "   *\n"
    content += "   * Controls how items are evicted from the cache when full.\n"
    content += "   * ARC (Adaptive Replacement Cache) provides good performance\n"
    content += "   * across diverse workloads by balancing recency and frequency.\n"
    content += "   */\n"
    content += "  eviction: {\n"

    if 'eviction' in optimal and 'overall' in optimal['eviction']:
        evict_opt = optimal['eviction']['overall']
        policy = evict_opt.get('policy', 'adaptive_arc')
        cache_size = evict_opt.get('cache_size', 512 * 1024 * 1024)
        hit_rate = evict_opt.get('hit_rate', 0.85)

        content += f"\n    /**\n"
        content += f"     * Eviction policy: {policy.upper()}\n"
        content += f"     *\n"
        content += f"     * Cache Size: {cache_size // (1024*1024)}MB\n"
        content += f"     * Expected Hit Rate: {hit_rate:.1%}\n"
        content += f"     */\n"
        content += f"    policy: '{policy}' as EvictionPolicy,\n"
        content += f"    maxSize: {cache_size},  // {cache_size // (1024*1024)}MB\n"
        content += f"    expectedHitRate: {hit_rate},\n"

    content += "  },\n"

    # Add ANN index config
    content += "\n  /**\n"
    content += "   * Approximate Nearest Neighbor (ANN) index settings\n"
    content += "   *\n"
    content += "   * Used for fast similarity search of KV-anchors.\n"
    content += "   * HNSW provides excellent recall with fast query times.\n"
    content += "   */\n"
    content += "  annIndex: {\n"

    if 'ann' in optimal:
        ann_opt = optimal['ann']
        algorithm = ann_opt.get('algorithm', 'hnsw')
        params = ann_opt.get('parameters', {})
        recall = ann_opt.get('recall', 0.95)
        query_time = ann_opt.get('query_time_ms', 1.0)

        content += f"\n    /**\n"
        content += f"     * ANN Algorithm: {algorithm.upper()}\n"
        content += f"     *\n"
        content += f"     * Expected Recall: {recall:.1%}\n"
        content += f"     * Expected Query Time: {query_time:.2f}ms\n"
        content += f"     */\n"
        content += f"    algorithm: '{algorithm}' as ANNAlgorithm,\n"
        content += f"    params: {json.dumps(params)},\n"
        content += f"    expectedRecall: {recall},\n"
        content += f"    expectedQueryTimeMs: {query_time},\n"

    content += "  },\n"

    # Add sizing config
    content += "\n  /**\n"
    content += "   * Cache sizing recommendations\n"
    content += "   *\n"
    content += "   * Optimal cache sizes for different workload types.\n"
    content += "   * Values determined by finding the \"knee\" of the hit-rate curve.\n"
    content += "   */\n"
    content += "  sizing: {\n"

    if 'sizing' in optimal and 'by_workload' in optimal['sizing']:
        for workload, sizing in optimal['sizing']['by_workload'].items():
            size_mb = sizing.get('size_mb', 100)
            hit_rate = sizing.get('hit_rate', 0.85)
            efficiency = sizing.get('efficiency', 0.001)

            content += f"\n    /**\n"
            content += f"     * {workload.upper()} workload\n"
            content += f"     *\n"
            content += f"     * Optimal Size: {size_mb:.1f}MB\n"
            content += f"     * Expected Hit Rate: {hit_rate:.1%}\n"
            content += f"     * Efficiency: {efficiency:.4f} per MB\n"
            content += f"     */\n"
            content += f"    {workload}: {{\n"
            content += f"      sizeMb: {size_mb},\n"
            content += f"      sizeBytes: {size_mb * 1024 * 1024},\n"
            content += f"      expectedHitRate: {hit_rate},\n"
            content += f"      efficiency: {efficiency},\n"
            content += f"    }},\n"

    content += "  },\n"

    # Add prefetch config
    content += "\n  /**\n"
    content += "   * Prefetching strategy settings\n"
    content += "   *\n"
    content += "   * Prefetching anticipates future cache accesses and loads them\n"
    content += "   * proactively to reduce latency. Markov-based prediction works\n"
    content += "   * well for sequential and repetitive access patterns.\n"
    content += "   */\n"
    content += "  prefetch: {\n"

    if 'prefetch' in optimal:
        prefetch_opt = optimal['prefetch']
        strategy = prefetch_opt.get('strategy', 'markov')
        params = prefetch_opt.get('parameters', {})
        efficiency = prefetch_opt.get('efficiency', 0.7)
        latency_reduction = prefetch_opt.get('latency_reduction', 0.3)

        content += f"\n    /**\n"
        content += f"     * Prefetch Strategy: {strategy.upper()}\n"
        content += f"     *\n"
        content += f"     * Expected Efficiency: {efficiency:.1%} (useful prefetches)\n"
        content += f"     * Latency Reduction: {latency_reduction:.1%}\n"
        content += f"     */\n"
        content += f"    enabled: true,\n"
        content += f"    strategy: '{strategy}' as const,\n"
        content += f"    params: {json.dumps(params)},\n"
        content += f"    expectedEfficiency: {efficiency},\n"
        content += f"    expectedLatencyReduction: {latency_reduction},\n"

    content += "  },\n"

    content += "} as const;\n\n"

    # Add type exports
    content += "/**\n"
    content += " * Type exports for KV-Cache configuration\n"
    content += " */\n"
    content += "export type KVCacheConfig = typeof KV_CACHE_CONFIG;\n\n"

    content += "/**\n"
    content += " * Compression configuration type\n"
    content += " */\n"
    content += "export type CompressionConfig = {\n"
    content += "  method: CompressionMethod;\n"
    content += "  ratio: number;\n"
    content += "  quality: number;\n"
    content += "  params?: Record<string, unknown>;\n"
    content += "};\n\n"

    content += "/**\n"
    content += " * Eviction configuration type\n"
    content += " */\n"
    content += "export type EvictionConfig = {\n"
    content += "  policy: EvictionPolicy;\n"
    content += "  maxSize: number;\n"
    content += "  expectedHitRate: number;\n"
    content += "};\n\n"

    content += "/**\n"
    content += " * ANN Index configuration type\n"
    content += " */\n"
    content += "export type ANNIndexConfig = {\n"
    content += "  algorithm: ANNAlgorithm;\n"
    content += "  params: Record<string, unknown>;\n"
    content += "  expectedRecall: number;\n"
    content += "  expectedQueryTimeMs: number;\n"
    content += "};\n"

    return content

def write_config_file(content: str, output_path: str):
    """Write configuration to TypeScript file"""
    # Ensure directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, 'w') as f:
        f.write(content)

    print(f"Configuration written to: {output_path}")

def main():
    """Main generation script"""
    print("="*70)
    print("GENERATING KV-CACHE CONFIGURATION")
    print("="*70)

    # Load results
    print("\nLoading optimization results...")
    results = load_results()

    if not results:
        print("\nWarning: No optimization results found!")
        print("Please run the optimizations first:")
        print("  python simulations/optimization/memory/run_all.py")
        return

    print(f"Loaded results for: {', '.join(results.keys())}")

    # Extract optimal parameters
    print("\nExtracting optimal parameters...")
    optimal = extract_optimal_params(results)

    # Generate TypeScript content
    print("\nGenerating TypeScript configuration...")
    content = generate_config_ts(optimal)

    # Write to file
    output_path = "src/core/kv/config.ts"
    write_config_file(content, output_path)

    # Also save JSON version
    json_path = "simulations/optimization/memory/kv_config.json"
    with open(json_path, 'w') as f:
        json.dump(optimal, f, indent=2)

    print(f"\nJSON configuration saved to: {json_path}")

    print("\n" + "="*70)
    print("CONFIGURATION GENERATION COMPLETE")
    print("="*70)

    print("\nGenerated files:")
    print(f"  1. {output_path} (TypeScript)")
    print(f"  2. {json_path} (JSON)")

    print("\nNext steps:")
    print("  1. Review the generated configuration")
    print("  2. Import in kvanchor.ts: import { KV_CACHE_CONFIG } from './kv/config'")
    print("  3. Use in your cache implementation")
    print("  4. Run tests to validate")

if __name__ == '__main__':
    main()
