/**
 * KV-Cache Configuration for POLLN
 *
 * Auto-generated by: simulations/optimization/memory/generate_config.py
 * Generation Date: 2026-03-07
 *
 * This file contains optimal parameters for the KV-cache system based on
 * comprehensive simulation testing. These parameters have been validated
 * across multiple workloads and access patterns.
 *
 * To regenerate: Run `python simulations/optimization/memory/run_all.py`
 *
 * Configuration Categories:
 * - compression: Compression strategies for different cache types
 * - eviction: Cache eviction policies and sizing
 * - annIndex: Approximate Nearest Neighbor index parameters
 * - sizing: Cache size recommendations per workload
 * - prefetch: Prefetching strategy settings
 */

import type { CompressionMethod, EvictionPolicy, ANNAlgorithm } from '../types';

/**
 * Main KV-Cache configuration object
 *
 * This configuration is optimized for production use across multiple
 * workload types: conversation, coding, analysis, and general mixed workloads.
 */
export const KV_CACHE_CONFIG = {
  /**
   * Compression settings for different KV-cache types
   *
   * Each cache type (attention, MLP, embedding, FFN) has different
   * characteristics and optimal compression strategies.
   */
  compression: {
    /**
     * ATTENTION cache compression
     *
     * Method: svd
     * Compression Ratio: 0.100 (10.0x reduction)
     * Expected Quality: 0.950 (cosine similarity)
     */
    attention: {
      method: 'svd' as CompressionMethod,
      ratio: 0.1,
      quality: 0.95,
      params: {"actual_ratio": 0.15},
    },

    /**
     * MLP cache compression
     *
     * Method: svd
     * Compression Ratio: 0.150 (6.7x reduction)
     * Expected Quality: 0.920 (cosine similarity)
     */
    mlp: {
      method: 'svd' as CompressionMethod,
      ratio: 0.15,
      quality: 0.92,
      params: {"actual_ratio": 0.2},
    },

    /**
     * EMBEDDING cache compression
     *
     * Method: quant_8bit
     * Compression Ratio: 0.250 (4.0x reduction)
     * Expected Quality: 0.980 (cosine similarity)
     */
    embedding: {
      method: 'quant_8bit' as CompressionMethod,
      ratio: 0.25,
      quality: 0.98,
      params: {"bits": 8, "compressed_size": 512},
    },
  },

  /**
   * Eviction policy settings
   *
   * Controls how items are evicted from the cache when full.
   * ARC (Adaptive Replacement Cache) provides good performance
   * across diverse workloads by balancing recency and frequency.
   */
  eviction: {
    /**
     * Eviction policy: ARC
     *
     * Cache Size: 512MB
     * Expected Hit Rate: 85.0%
     */
    policy: 'arc' as EvictionPolicy,
    maxSize: 536870912,  // 512MB
    expectedHitRate: 0.85,
  },

  /**
   * Approximate Nearest Neighbor (ANN) index settings
   *
   * Used for fast similarity search of KV-anchors.
   * HNSW provides excellent recall with fast query times.
   */
  annIndex: {
    /**
     * ANN Algorithm: hnsw
     *
     * Expected Recall: 95.0%
     * Expected Query Time: 1.50ms
     */
    algorithm: 'hnsw' as ANNAlgorithm,
    params: {"M": 16, "efConstruction": 200, "efSearch": 50},
    expectedRecall: 0.95,
    expectedQueryTimeMs: 1.5,
  },

  /**
   * Cache sizing recommendations
   *
   * Optimal cache sizes for different workload types.
   * Values determined by finding the "knee" of the hit-rate curve.
   */
  sizing: {
    /**
     * CONVERSATION workload
     *
     * Optimal Size: 100.0MB
     * Expected Hit Rate: 92.0%
     * Efficiency: 0.0092 per MB
     */
    conversation: {
      sizeMb: 100,
      sizeBytes: 104857600,
      expectedHitRate: 0.92,
      efficiency: 0.0092,
    },

    /**
     * CODING workload
     *
     * Optimal Size: 200.0MB
     * Expected Hit Rate: 88.0%
     * Efficiency: 0.0044 per MB
     */
    coding: {
      sizeMb: 200,
      sizeBytes: 209715200,
      expectedHitRate: 0.88,
      efficiency: 0.0044,
    },

    /**
     * ANALYSIS workload
     *
     * Optimal Size: 500.0MB
     * Expected Hit Rate: 85.0%
     * Efficiency: 0.0017 per MB
     */
    analysis: {
      sizeMb: 500,
      sizeBytes: 524288000,
      expectedHitRate: 0.85,
      efficiency: 0.0017,
    },

    /**
     * GENERAL workload
     *
     * Optimal Size: 256.0MB
     * Expected Hit Rate: 90.0%
     * Efficiency: 0.0035 per MB
     */
    general: {
      sizeMb: 256,
      sizeBytes: 268435456,
      expectedHitRate: 0.9,
      efficiency: 0.0035,
    },
  },

  /**
   * Prefetching strategy settings
   *
   * Prefetching anticipates future cache accesses and loads them
   * proactively to reduce latency. Markov-based prediction works
   * well for sequential and repetitive access patterns.
   */
  prefetch: {
    /**
     * Prefetch Strategy: markov
     *
     * Expected Efficiency: 75.0% (useful prefetches)
     * Latency Reduction: 35.0%
     */
    enabled: true,
    strategy: 'markov' as const,
    params: {"prefetch_window": 5, "prefetch_threshold": 0.3},
    expectedEfficiency: 0.75,
    expectedLatencyReduction: 0.35,
  },
} as const;

/**
 * Type exports for KV-Cache configuration
 */
export type KVCacheConfig = typeof KV_CACHE_CONFIG;

/**
 * Compression configuration type
 */
export type CompressionConfig = {
  method: CompressionMethod;
  ratio: number;
  quality: number;
  params?: Record<string, unknown>;
};

/**
 * Eviction configuration type
 */
export type EvictionConfig = {
  policy: EvictionPolicy;
  maxSize: number;
  expectedHitRate: number;
};

/**
 * ANN Index configuration type
 */
export type ANNIndexConfig = {
  algorithm: ANNAlgorithm;
  params: Record<string, unknown>;
  expectedRecall: number;
  expectedQueryTimeMs: number;
};

/**
 * Sizing configuration type
 */
export type SizingConfig = {
  sizeMb: number;
  sizeBytes: number;
  expectedHitRate: number;
  efficiency: number;
};

/**
 * Prefetch configuration type
 */
export type PrefetchConfig = {
  enabled: boolean;
  strategy: string;
  params: Record<string, unknown>;
  expectedEfficiency: number;
  expectedLatencyReduction: number;
};
