/**
 * POLLN Reasoning Domain Types
 *
 * TypeScript type definitions for the reasoning domain configuration.
 * These types support the config generated by Python simulations.
 */

// ========================================
// Core Domain Types
// ========================================

/**
 * Main reasoning domain configuration
 */
export interface ReasoningDomainConfig {
  dialogue: DialogueConfig;
  chainOfThought: ChainOfThoughtConfig;
  context: ContextConfig;
  depth: DepthConfig;
  consistency: ConsistencyConfig;
  agents: AgentComposition;
  metadata: ConfigMetadata;
}

/**
 * Configuration metadata
 */
export interface ConfigMetadata {
  version: string;
  generated_by: string;
  source: string;
}

// ========================================
// Dialogue Management Types
// ========================================

/**
 * Dialogue management configuration
 */
export interface DialogueConfig {
  maxTurns: number;
  contextWindow: string;
  summarizationThreshold: number;
  entityTracking: boolean;
  personaConsistency: string;
  temperature?: number;
  turnManagement?: TurnManagementConfig;
  coherence?: CoherenceConfig;
}

/**
 * Turn management configuration
 */
export interface TurnManagementConfig {
  maxConsecutiveTurns: number;
  interruptionAllowed: boolean;
}

/**
 * Coherence targets configuration
 */
export interface CoherenceConfig {
  target: number;
  minContextRetention: number;
}

// ========================================
// Chain-of-Thought Types
// ========================================

/**
 * Chain-of-thought reasoning configuration
 */
export interface ChainOfThoughtConfig {
  enabled: boolean;
  checkpoints: CheckpointConfig;
  selfConsistency: SelfConsistencyConfig;
  verifier: VerifierConfig;
  maxSteps: number;
  stepConfidenceThreshold: number;
}

/**
 * Checkpoint configuration
 */
export interface CheckpointConfig {
  placement: 'auto' | 'fixed' | 'adaptive';
  interval?: number;
  utilizationTarget?: number;
}

/**
 * Self-consistency sampling configuration
 */
export interface SelfConsistencyConfig {
  samples: number;
  aggregation: 'majority' | 'weighted' | 'ranked';
  temperature: number;
}

/**
 * Verifier configuration
 */
export interface VerifierConfig {
  enabled: boolean;
  confidence: number;
  strategy?: 'accuracy' | 'quality' | 'both';
}

// ========================================
// Context Management Types
// ========================================

/**
 * Context management configuration
 */
export interface ContextConfig {
  compression: CompressionConfig;
  kvCache: KVCacheConfig;
  entityTracking: EntityTrackingConfig;
  memoryRetrieval: MemoryRetrievalConfig;
}

/**
 * Compression configuration
 */
export interface CompressionConfig {
  strategy: 'sliding_window' | 'summarization' | 'hierarchical' | 'kv_cache' | 'hybrid';
  summarizationThreshold: number;
  hierarchicalLevels: number;
}

/**
 * KV-Cache configuration
 */
export interface KVCacheConfig {
  enabled: boolean;
  strategy: 'attention_prior' | 'lru' | 'lfu';
  maxSize: string;
  cacheBudget: number;
  evictionPolicy: 'lru' | 'lfu' | 'attention_based';
}

/**
 * Entity tracking configuration
 */
export interface EntityTrackingConfig {
  enabled: boolean;
  relationshipInference: boolean;
  activeWindow: number;
}

/**
 * Memory retrieval configuration
 */
export interface MemoryRetrievalConfig {
  enabled: boolean;
  topK: number;
  similarity: 'cosine' | 'euclidean' | 'dot_product';
  timeDecay: boolean;
  importanceWeight: number;
}

// ========================================
// Reasoning Depth Types
// ========================================

/**
 * Reasoning depth configuration
 */
export interface DepthConfig {
  shallow: DepthModeConfig;
  medium: DepthModeConfig;
  deep: DepthModeConfig;
  adaptive: AdaptiveDepthConfig;
  explorationStrategy: ExplorationStrategyConfig;
}

/**
 * Depth mode configuration
 */
export interface DepthModeConfig {
  maxSteps: number;
  breadth: number;
  beamWidth: number;
  useCase: string;
}

/**
 * Adaptive depth configuration
 */
export interface AdaptiveDepthConfig {
  enabled: boolean;
  complexityThreshold: number;
  features: string[];
}

/**
 * Exploration strategy configuration
 */
export interface ExplorationStrategyConfig {
  default: string;
  alternatives: string[];
  selectionCriteria: string;
}

// ========================================
// Consistency Types
// ========================================

/**
 * Consistency validation configuration
 */
export interface ConsistencyConfig {
  selfConsistency: ConsistencyCheckConfig;
  factualConsistency: ConsistencyCheckConfig;
  temporalConsistency: ConsistencyCheckConfig;
  logicalConsistency: ConsistencyCheckConfig;
  personaConsistency: ConsistencyCheckConfig;
}

/**
 * Individual consistency check configuration
 */
export interface ConsistencyCheckConfig {
  enabled: boolean;
  severityThreshold: string;
  confidenceThreshold?: number;
  knowledgeBase?: boolean;
  historyWindow?: number;
  checkCircularReasoning?: boolean;
  checkNonSequitur?: boolean;
  toneChecking?: boolean;
  styleChecking?: boolean;
}

// ========================================
// Agent Composition Types
// ========================================

/**
 * Agent composition for reasoning domain
 */
export interface AgentComposition {
  reasoner: AgentConfig;
  verifier: AgentConfig;
  summarizer: AgentConfig;
  dialogueManager: AgentConfig;
  consistencyChecker: AgentConfig;
  entityTracker: AgentConfig;
}

/**
 * Individual agent configuration
 */
export interface AgentConfig {
  type: 'role' | 'task' | 'core';
  expertise: string;
  checkpoints?: number;
  temperature?: number;
  valueNetwork?: string;
  confidenceThreshold?: number;
  compressionRatio?: number;
  maxSummaryLength?: number;
  maxTurns?: number;
  contextRetention?: number;
  severityThreshold?: string;
  activeWindow?: number;
}

// ========================================
// Simulation Result Types
// ========================================

/**
 * Dialogue simulation results
 */
export interface DialogueSimulationResults {
  dialogue_results: Record<string, DialogueMetrics>;
  compression_results: Record<string, CompressionResult>;
  optimal_config: any;
  expected_metrics: any;
}

/**
 * Dialogue metrics
 */
export interface DialogueMetrics {
  turns: number;
  coherence: number;
  relevance: number;
  engagement: number;
  consistency: number;
  context_retention: number;
}

/**
 * Compression result
 */
export interface CompressionResult {
  strategy: string;
  original_turns: number;
  compressed_turns: number;
  compression_ratio: number;
  information_retention: number;
}

/**
 * Chain-of-thought results
 */
export interface ChainOfThoughtResults {
  metrics: {
    accuracy: number;
    reasoning_quality: number;
    consensus_rate: number;
    avg_confidence: number;
    avg_steps: number;
    checkpoint_utilization: number;
    verification_rate: number;
  };
  checkpoint_optimization: Record<string, any>;
  optimal_config: any;
}

/**
 * Context tracking results
 */
export interface ContextTrackingResults {
  strategy_comparison: Record<string, ContextMetrics>;
  optimal_config: any;
}

/**
 * Context metrics
 */
export interface ContextMetrics {
  compression_ratio: number;
  information_retention: number;
  retrieval_accuracy: number;
  entity_tracking_accuracy: number;
  summary_quality: number;
  memory_efficiency: number;
}

/**
 * Reasoning depth results
 */
export interface ReasoningDepthResults {
  task_results: Record<string, any>;
  strategy_comparison: Record<string, any>;
  optimal_config: any;
}

/**
 * Consistency results
 */
export interface ConsistencyResults {
  test_results: any[];
  metrics: {
    violation_rate: number;
    average_score: number;
  };
  optimal_config: any;
}

// ========================================
// Utility Types
// ========================================

/**
 * Configuration override type
 */
export type ConfigOverride<T> = Partial<T>;

/**
 * Agent type union
 */
export type AgentType = 'role' | 'task' | 'core';

/**
 * Dialogue type enum
 */
export enum DialogueType {
  SHORT_CONTEXT = 'short_context',
  LONG_CONTEXT = 'long_context',
  MULTI_PARTY = 'multi_party',
  TASK_ORIENTED = 'task_oriented',
  SOCIAL = 'social'
}

/**
 * Reasoning mode enum
 */
export enum ReasoningMode {
  SHALLOW = 'shallow',
  MEDIUM = 'medium',
  DEEP = 'deep',
  ADAPTIVE = 'adaptive'
}

/**
 * Exploration strategy enum
 */
export enum ExplorationStrategy {
  TREE_OF_THOUGHTS = 'tree_of_thoughts',
  ITERATIVE_REFINEMENT = 'iterative_refinement',
  DEBATE = 'debate',
  BEAM_SEARCH = 'beam_search',
  MONTE_CARLO = 'monte_carlo'
}

/**
 * Compression strategy enum
 */
export enum CompressionStrategy {
  SLIDING_WINDOW = 'sliding_window',
  SUMMARIZATION = 'summarization',
  HIERARCHICAL = 'hierarchical',
  KV_CACHE = 'kv_cache',
  HYBRID = 'hybrid'
}

/**
 * Consistency type enum
 */
export enum ConsistencyType {
  SELF_CONSISTENCY = 'self_consistency',
  FACTUAL_CONSISTENCY = 'factual_consistency',
  TEMPORAL_CONSISTENCY = 'temporal_consistency',
  LOGICAL_CONSISTENCY = 'logical_consistency',
  PERSONA_CONSISTENCY = 'persona_consistency'
}

// ========================================
// Helper Types for Generics
// ========================================

/**
 * Key-value pair type
 */
export type KeyValuePair<K extends string | number, V> = {
  key: K;
  value: V;
};

/**
 * Optional configuration
 */
export type OptionalConfig<T> = {
  [P in keyof T]?: T[P];
};

/**
 * Deep partial type
 */
export type DeepPartial<T> = {
  [P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P];
};

// ========================================
// Export Default
// ========================================

export default {
  ReasoningDomainConfig,
  DialogueConfig,
  ChainOfThoughtConfig,
  ContextConfig,
  DepthConfig,
  ConsistencyConfig,
  AgentComposition,
  DialogueType,
  ReasoningMode,
  ExplorationStrategy,
  CompressionStrategy,
  ConsistencyType
};
