/**
 * POLLN Configuration Tiers
 *
 * Auto-generated from Pareto-optimal configurations
 * Generated by: simulations/advanced/multiobjective/run_all.py
 *
 * Categories:
 * - Accuracy vs Cost
 * - Speed vs Quality
 * - Robustness vs Efficiency
 * - Scalability vs Complexity
 *
 * Usage:
 * ```typescript
 * import { CONFIG_TIERS } from '@polln/core/config/tiers';
 *
 * // Use budget tier
 * const config = CONFIG_TIERS.ACCURACY_COST_BUDGET;
 *
 * // Use production scenario
 * import productionConfig from './scenarios.json';
 * ```
 */

export interface PollnConfigTier {
  // Model parameters
  model_size?: string;
  checkpoint_frequency?: number;
  cache_size?: string;
  kv_cache_size?: string;

  // Inference parameters
  batch_size?: number;
  compression_level?: number;
  temperature?: number;
  top_p?: number;
  max_tokens?: number;

  // Reliability parameters
  replication_factor?: number;
  monitoring_level?: number;
  backup_enabled?: boolean;
  backup_frequency_hours?: number;
  health_check_interval_sec?: number;
  circuit_breaker_threshold?: number;
  retry_policy?: string;
  max_retries?: number;
  timeout_multiplier?: number;
  use_quorum?: boolean;
  disaster_recovery_enabled?: boolean;

  // Scalability parameters
  colony_size?: number;
  topology_depth?: number;
  agent_types?: number;
  decentralization_level?: number;
  horizontal_scaling?: boolean;
  auto_scaling?: boolean;
  load_balancing_strategy?: string;
  cache_sharding?: boolean;
  federation_enabled?: boolean;
  meta_tile_ratio?: number;
  communication_pattern?: string;

  // Advanced features
  use_speculative_decoding?: boolean;
  use_quantization?: boolean;
  use_federated?: boolean;

  // Expected metrics
  expected_accuracy?: number;
  expected_latency_ms?: number;
  expected_availability?: string;
  expected_throughput?: number;
  expected_cost_multiplier?: number;
  expected_complexity?: number;
  expected_hourly_cost?: number;

  // Target objective
  target: string;
}

/**
 * Default tier configurations
 *
 * These are placeholder values. Run the Pareto optimizations to generate
 * real configurations:
 *
 * ```bash
 * cd simulations/advanced/multiobjective
 * python run_all.py
 * ```
 */
export const CONFIG_TIERS: Record<string, PollnConfigTier> = {
  // Accuracy vs Cost tiers
  ACCURACY_COST_BUDGET: {
    model_size: '10M',
    checkpoint_frequency: 5,
    cache_size: '128MB',
    batch_size: 1,
    compression_level: 0.8,
    temperature: 1.0,
    use_federated: false,
    replication_factor: 1,
    expected_accuracy: 0.85,
    expected_hourly_cost: 0.30,
    target: 'minimum_cost'
  },

  ACCURACY_COST_STANDARD: {
    model_size: '100M',
    checkpoint_frequency: 10,
    cache_size: '512MB',
    batch_size: 16,
    compression_level: 0.5,
    temperature: 0.7,
    use_federated: true,
    replication_factor: 2,
    expected_accuracy: 0.90,
    expected_hourly_cost: 1.00,
    target: 'balanced'
  },

  ACCURACY_COST_PERFORMANCE: {
    model_size: '500M',
    checkpoint_frequency: 20,
    cache_size: '2GB',
    batch_size: 32,
    compression_level: 0.2,
    temperature: 0.5,
    use_federated: true,
    replication_factor: 3,
    expected_accuracy: 0.93,
    expected_hourly_cost: 2.00,
    target: 'high_quality'
  },

  // Speed vs Quality tiers
  SPEED_QUALITY_REALTIME: {
    model_size: '10M',
    batch_size: 1,
    max_parallel_requests: 8,
    kv_cache_size: '256MB',
    compression_level: 0.5,
    use_speculative_decoding: true,
    use_quantization: true,
    temperature: 0.7,
    top_p: 0.9,
    max_tokens: 500,
    expected_latency_ms: 75,
    expected_quality: 0.85,
    expected_throughput: 50,
    target: 'minimum_latency'
  },

  SPEED_QUALITY_INTERACTIVE: {
    model_size: '100M',
    batch_size: 8,
    max_parallel_requests: 16,
    kv_cache_size: '512MB',
    compression_level: 0.3,
    use_speculative_decoding: false,
    use_quantization: false,
    temperature: 0.7,
    top_p: 0.95,
    max_tokens: 1000,
    expected_latency_ms: 350,
    expected_quality: 0.90,
    expected_throughput: 100,
    target: 'speed_quality_balance'
  },

  // Robustness vs Efficiency tiers
  ROBUSTNESS_EFFICIENCY_BASIC: {
    replication_factor: 1,
    checkpoint_interval_sec: 60,
    backup_enabled: false,
    monitoring_level: 0,
    health_check_interval_sec: 60,
    circuit_breaker_threshold: 3,
    retry_policy: 'none',
    max_retries: 0,
    timeout_multiplier: 1.0,
    use_quorum: false,
    disaster_recovery_enabled: false,
    expected_availability: '99.0%',
    expected_cost_multiplier: 1.0,
    target: 'basic_reliability'
  },

  ROBUSTNESS_EFFICIENCY_HIGH: {
    replication_factor: 3,
    checkpoint_interval_sec: 30,
    backup_enabled: true,
    backup_frequency_hours: 24,
    monitoring_level: 2,
    health_check_interval_sec: 30,
    circuit_breaker_threshold: 5,
    retry_policy: 'exponential',
    max_retries: 3,
    timeout_multiplier: 1.5,
    use_quorum: true,
    disaster_recovery_enabled: false,
    expected_availability: '99.9%',
    expected_cost_multiplier: 1.5,
    target: 'high_availability'
  },

  // Scalability vs Complexity tiers
  SCALABILITY_COMPLEXITY_SMALL: {
    colony_size: 50,
    topology_depth: 2,
    agent_types: 3,
    decentralization_level: 0.3,
    horizontal_scaling: false,
    auto_scaling: false,
    load_balancing_strategy: 'round_robin',
    cache_sharding: false,
    federation_enabled: false,
    meta_tile_ratio: 0.1,
    communication_pattern: 'star',
    expected_throughput: 200,
    expected_complexity: 0.2,
    target: 'small_scale'
  },

  SCALABILITY_COMPLEXITY_MEDIUM: {
    colony_size: 250,
    topology_depth: 4,
    agent_types: 8,
    decentralization_level: 0.5,
    horizontal_scaling: true,
    auto_scaling: false,
    load_balancing_strategy: 'least_loaded',
    cache_sharding: true,
    federation_enabled: false,
    meta_tile_ratio: 0.3,
    communication_pattern: 'hierarchical',
    expected_throughput: 1500,
    expected_complexity: 0.5,
    target: 'medium_scale'
  }
};

/**
 * Scenario-based recommended configurations
 */
export const SCENARIO_CONFIGS: Record<string, PollnConfigTier> = {
  PRODUCTION: {
    ...CONFIG_TIERS.ACCURACY_COST_STANDARD,
    ...CONFIG_TIERS.ROBUSTNESS_EFFICIENCY_HIGH,
    ...CONFIG_TIERS.SPEED_QUALITY_INTERACTIVE
  },

  DEVELOPMENT: {
    ...CONFIG_TIERS.ACCURACY_COST_BUDGET,
    ...CONFIG_TIERS.ROBUSTNESS_EFFICIENCY_BASIC
  },

  EDGE: {
    ...CONFIG_TIERS.SPEED_QUALITY_REALTIME,
    ...CONFIG_TIERS.ACCURACY_COST_BUDGET
  },

  RESEARCH: {
    ...CONFIG_TIERS.ACCURACY_COST_PERFORMANCE,
    batch_size: 64,
    target: 'maximum_quality'
  },

  REALTIME: {
    ...CONFIG_TIERS.SPEED_QUALITY_REALTIME,
    ...CONFIG_TIERS.ROBUSTNESS_EFFICIENCY_HIGH
  },

  BATCH: {
    ...CONFIG_TIRES.SCALABILITY_COMPLEXITY_MEDIUM,
    batch_size: 64,
    target: 'maximum_throughput'
  }
};

/**
 * Helper function to get configuration by tier name
 */
export function getConfig(tierName: string): PollnConfigTier | undefined {
  return CONFIG_TIERS[tierName];
}

/**
 * Helper function to get scenario configuration
 */
export function getScenarioConfig(scenarioName: string): PollnConfigTier | undefined {
  return SCENARIO_CONFIGS[scenarioName];
}

/**
 * Helper function to merge multiple configurations
 */
export function mergeConfigs(...configs: Partial<PollnConfigTier>[]): PollnConfigTier {
  return Object.assign({}, ...configs) as PollnConfigTier;
}

/**
 * Helper function to validate configuration meets constraints
 */
export function validateConfig(
  config: PollnConfigTier,
  constraints: Partial<{
    max_latency_ms: number;
    min_availability: number;
    max_cost_multiplier: number;
    min_accuracy: number;
  }>
): boolean {
  if (constraints.max_latency_ms && config.expected_latency_ms) {
    if (config.expected_latency_ms > constraints.max_latency_ms) {
      return false;
    }
  }

  if (constraints.min_availability && config.expected_availability) {
    const availability = parseFloat(config.expected_availability);
    if (availability < constraints.min_availability * 100) {
      return false;
    }
  }

  if (constraints.max_cost_multiplier && config.expected_cost_multiplier) {
    if (config.expected_cost_multiplier > constraints.max_cost_multiplier) {
      return false;
    }
  }

  if (constraints.min_accuracy && config.expected_accuracy) {
    if (config.expected_accuracy < constraints.min_accuracy) {
      return false;
    }
  }

  return true;
}

export default CONFIG_TIERS;
