/**
 * POLLN Reasoning Domain Configuration
 *
 * This configuration is auto-generated from simulation results.
 * It provides optimal settings for dialogue and reasoning tasks.
 *
 * Generated by: reasoning_optimizer.py
 * Version: 1.0.0
 */

import { ReasoningDomainConfig, DialogueConfig, ChainOfThoughtConfig,
         ContextConfig, DepthConfig, ConsistencyConfig, AgentComposition } from './types';

export const REASONING_DOMAIN_CONFIG: ReasoningDomainConfig = {

  // ========================================
  // Dialogue Management
  // ========================================
  dialogue: {
  maxTurns: 100,
  contextWindow: '128K',
  summarizationThreshold: 10,
  entityTracking: true,
  personaConsistency: 'high',
  temperature: 0.8,
  turnManagement: {
    maxConsecutiveTurns: 3,
    interruptionAllowed: false
  },
  coherence: {
    target: 0.85,
    minContextRetention: 0.7
  }
},

  // ========================================
  // Chain-of-Thought Reasoning
  // ========================================
  chainOfThought: {
  enabled: true,
  checkpoints: {
    placement: 'auto'
  },
  selfConsistency: {
    samples: 5,
    aggregation: 'majority',
    temperature: 0.7
  },
  verifier: {
    enabled: true,
    confidence: 0.7
  },
  maxSteps: 20,
  stepConfidenceThreshold: 0.6
},

  // ========================================
  // Context Management
  // ========================================
  context: {
  compression: {
    strategy: 'hybrid',
    summarizationThreshold: 10,
    hierarchicalLevels: 3
  },
  kvCache: {
    enabled: true,
    strategy: 'attention_prior',
    maxSize: '1GB',
    cacheBudget: 20,
    evictionPolicy: 'lru'
  },
  entityTracking: {
    enabled: true,
    relationshipInference: true,
    activeWindow: 10
  },
  memoryRetrieval: {
    enabled: true,
    topK: 5,
    similarity: 'cosine',
    timeDecay: true,
    importanceWeight: 1.0
  }
},

  // ========================================
  // Reasoning Depth Configuration
  // ========================================
  depth: {
  shallow: {
    maxSteps: 3,
    breadth: 10,
    beamWidth: 5,
    useCase: 'simple_tasks'
  },
  medium: {
    maxSteps: 7,
    breadth: 5,
    beamWidth: 3,
    useCase: 'moderate_complexity'
  },
  deep: {
    maxSteps: 15,
    breadth: 3,
    beamWidth: 2,
    useCase: 'complex_reasoning'
  },
  adaptive: {
    enabled: true,
    complexityThreshold: 0.5,
    features: [
      'num_entities',
'question_length',
'semantic_complexity'
    ]
  },
  explorationStrategy: {
    default: 'tree_of_thoughts',
    alternatives: [
      'iterative_refinement',
'debate',
'beam_search'
    ]
  }
},

  // ========================================
  // Consistency Validation
  // ========================================
  consistency: {
  selfConsistency: {
    enabled: true,
    severityThreshold: 'medium'
  },
  factualConsistency: {
    enabled: true,
    knowledgeBase: true,
    confidenceThreshold: 0.7
  },
  temporalConsistency: {
    enabled: true,
    historyWindow: 5,
    severityThreshold: 'medium'
  },
  logicalConsistency: {
    enabled: true,
    checkCircularReasoning: true,
    checkNonSequitur: true
  },
  personaConsistency: {
    enabled: true,
    toneChecking: true,
    styleChecking: true
  }
},

  // ========================================
  // Agent Composition
  // ========================================
  agents: {
  reasoner: {
    type: 'role',
    expertise: 'logical_reasoning',
    checkpoints: 20,
    temperature: 0.5,
    valueNetwork: 'reasoning_quality'
  },
  verifier: {
    type: 'task',
    expertise: 'verification',
    valueNetwork: 'verification_confidence',
    confidenceThreshold: 0.7
  },
  summarizer: {
    type: 'task',
    expertise: 'summarization',
    compressionRatio: 0.3,
    maxSummaryLength: 500
  },
  dialogueManager: {
    type: 'role',
    expertise: 'dialogue_coordination',
    maxTurns: 100,
    contextRetention: 0.8
  },
  consistencyChecker: {
    type: 'task',
    expertise: 'consistency_validation',
    severityThreshold: 'medium'
  },
  entityTracker: {
    type: 'task',
    expertise: 'entity_extraction',
    activeWindow: 10
  }
},

  metadata: {
    version: '1.0.0',
    generated_by: 'reasoning_optimizer.py',
    source: 'POLLN reasoning domain simulations',
  }
};


// ========================================
// Convenience Functions
// ========================================

/**
 * Get dialogue configuration with overrides
 */
export function getDialogueConfig(overrides?: Partial<DialogueConfig>): DialogueConfig {
  return {
    ...REASONING_DOMAIN_CONFIG.dialogue,
    ...overrides
  };
}

/**
 * Get chain-of-thought configuration with overrides
 */
export function getCOTConfig(overrides?: Partial<ChainOfThoughtConfig>): ChainOfThoughtConfig {
  return {
    ...REASONING_DOMAIN_CONFIG.chainOfThought,
    ...overrides
  };
}

/**
 * Get context configuration with overrides
 */
export function getContextConfig(overrides?: Partial<ContextConfig>): ContextConfig {
  return {
    ...REASONING_DOMAIN_CONFIG.context,
    ...overrides
  };
}

/**
 * Get depth configuration for specific task complexity
 */
export function getDepthConfig(complexity: 'shallow' | 'medium' | 'deep'): any {
  return REASONING_DOMAIN_CONFIG.depth[complexity];
}

/**
 * Check if consistency validation is enabled
 */
export function isConsistencyEnabled(type: keyof ConsistencyConfig): boolean {
  return REASONING_DOMAIN_CONFIG.consistency[type]?.enabled ?? false;
}

/**
 * Get agent configuration for reasoning tasks
 */
export function getReasoningAgent(agentType: keyof AgentComposition): any {
  return REASONING_DOMAIN_CONFIG.agents[agentType];
}
