"""
TypeScript Config Generator

Reads optimization results and generates TypeScript constants file
with optimal hyperparameters for POLLN components.

Output: src/core/config/optimized.ts
"""

import json
from pathlib import Path
from typing import Dict, Any


def format_value(value: Any) -> str:
    """
    Format a value for TypeScript output.

    Args:
        value: Value to format

    Returns:
        Formatted string representation
    """
    if isinstance(value, float):
        # Use appropriate precision
        if abs(value) < 0.001 or abs(value) > 1000:
            return f"{value:.6e}"
        else:
            return f"{value:.6f}"
    elif isinstance(value, str):
        # Escape strings
        return f"'{value}'"
    elif isinstance(value, bool):
        return str(value).lower()
    elif isinstance(value, list):
        items = [format_value(v) for v in value]
        return f"[{', '.join(items)}]"
    elif isinstance(value, dict):
        items = [f"  {k}: {format_value(v)}" for k, v in value.items()]
        return "{\n" + ",\n".join(items) + "\n}"
    elif value is None:
        return 'null'
    else:
        return str(value)


def generate_typescript_config(results: Dict) -> str:
    """
    Generate TypeScript configuration file content.

    Args:
        results: Unified optimization results

    Returns:
        TypeScript file content
    """
    output = []

    # Header
    output.append("// Auto-generated by simulations/optimization/hyperparams/")
    output.append("// DO NOT EDIT MANUALLY")
    output.append("// Regenerate with: python simulations/optimization/hyperparams/run_all.py")
    output.append("")
    output.append("/**")
    output.append(" * Optimized hyperparameters for POLLN components.")
    output.append(" * ")
    output.append(" * These values were found through Bayesian optimization and grid search")
    output.append(" * to maximize performance, convergence speed, and stability.")
    output.append(" * ")
    output.append(" * @module config/optimized")
    output.append(" */")
    output.append("")

    # Extract parameters
    opts = results.get('optimizations', {})

    # Plinko configuration
    if 'plinko_temperature' in opts:
        plinko_params = opts['plinko_temperature']['best_parameters']
        output.append("/** Plinko temperature schedule parameters */")
        output.append("export const PLINKO_CONFIG = {")
        output.append(f"  /** Initial temperature for exploration */")
        output.append(f"  initialTemperature: {format_value(plinko_params.get('initial_temp', 2.5))},")
        output.append(f"  /** Temperature schedule type */")
        output.append(f"  schedule: {format_value(plinko_params.get('schedule_type', 'exponential'))},")
        output.append(f"  /** Decay rate for temperature annealing */")
        output.append(f"  decayRate: {format_value(plinko_params.get('decay_rate', 0.995))},")
        output.append(f"  /** Minimum temperature floor */")
        output.append(f"  minTemperature: {format_value(plinko_params.get('min_temp', 0.1))}")
        output.append("} as const;")
        output.append("")

    # TD(λ) configuration
    if 'td_lambda_optimization' in opts:
        td_params = opts['td_lambda_optimization']['best_parameters']
        output.append("/** TD(λ) reinforcement learning parameters */")
        output.append("export const TD_LAMBDA_CONFIG = {")
        output.append(f"  /** Eligibility trace decay [0, 1] */")
        output.append(f"  lambda: {format_value(td_params.get('lambda', 0.95))},")
        output.append(f"  /** Learning rate [0, 1] */")
        output.append(f"  alpha: {format_value(td_params.get('alpha', 0.1))},")
        output.append(f"  /** Discount factor [0, 1] */")
        output.append(f"  gamma: {format_value(td_params.get('gamma', 0.99))}")
        output.append("} as const;")
        output.append("")

    # VAE configuration
    if 'vae_architecture' in opts:
        vae_params = opts['vae_architecture']['best_parameters']
        output.append("/** VAE world model architecture parameters */")
        output.append("export const VAE_CONFIG = {")
        output.append(f"  /** Latent dimension size */")
        output.append(f"  latentDim: {format_value(vae_params.get('latent_dim', 128))},")
        output.append(f"  /** β-VAE parameter (KL divergence weight) */")
        output.append(f"  beta: {format_value(vae_params.get('beta', 1.0))},")
        output.append(f"  /** Capacity limit for KL divergence (null = no limit) */")
        output.append(f"  capacity: {format_value(vae_params.get('capacity', None))}")
        output.append("} as const;")
        output.append("")

    # Graph evolution configuration
    if 'graph_evolution_params' in opts:
        evo_params = opts['graph_evolution_params']['best_parameters']
        output.append("/** Graph evolution parameters */")
        output.append("export const GRAPH_EVOLUTION_CONFIG = {")
        output.append(f"  /** Threshold for pruning weak connections */")
        output.append(f"  pruningThreshold: {format_value(evo_params.get('pruning_threshold', 0.3))},")
        output.append(f"  /** Rate for grafting new connections */")
        output.append(f"  graftingRate: {format_value(evo_params.get('grafting_rate', 0.1))},")
        output.append(f"  /** Resolution for community detection */")
        output.append(f"  clusteringResolution: {format_value(evo_params.get('clustering_resolution', 1.0))}")
        output.append("} as const;")
        output.append("")

    # META tile configuration
    if 'meta_differentiation' in opts:
        meta_params = opts['meta_differentiation']['best_parameters']
        output.append("/** META tile differentiation parameters */")
        output.append("export const META_CONFIG = {")
        output.append(f"  /** Rate of response to signals */")
        output.append(f"  signalResponseRate: {format_value(meta_params.get('signal_response_rate', 0.1))},")
        output.append(f"  /** Threshold for differentiation */")
        output.append(f"  differentiationThreshold: {format_value(meta_params.get('differentiation_threshold', 0.9))},")
        output.append(f"  /** Plasticity rule for weight updates */")
        output.append(f"  plasticityRule: {format_value(meta_params.get('plasticity_rule', 'oja'))}")
        output.append("} as const;")
        output.append("")

    # Unified config object
    output.append("/** Unified configuration object */")
    output.append("export const OPTIMIZED_CONFIG = {")

    if 'plinko_temperature' in opts:
        output.append("  plinko: PLINKO_CONFIG,")

    if 'td_lambda_optimization' in opts:
        output.append("  tdLambda: TD_LAMBDA_CONFIG,")

    if 'vae_architecture' in opts:
        output.append("  vae: VAE_CONFIG,")

    if 'graph_evolution_params' in opts:
        output.append("  evolution: GRAPH_EVOLUTION_CONFIG,")

    if 'meta_differentiation' in opts:
        output.append("  meta: META_CONFIG,")

    output.append("} as const;")
    output.append("")

    # Type definitions
    output.append("// Type definitions")
    output.append("export type PlinkoConfig = typeof PLINKO_CONFIG;")
    output.append("export type TDLambdaConfig = typeof TD_LAMBDA_CONFIG;")
    output.append("export type VAEConfig = typeof VAE_CONFIG;")
    output.append("export type GraphEvolutionConfig = typeof GRAPH_EVOLUTION_CONFIG;")
    output.append("export type MetaConfig = typeof META_CONFIG;")
    output.append("export type OptimizedConfig = typeof OPTIMIZED_CONFIG;")
    output.append("")

    return "\n".join(output)


def generate_json_config(results: Dict) -> Dict:
    """
    Generate clean JSON configuration.

    Args:
        results: Unified optimization results

    Returns:
        Clean JSON configuration dictionary
    """
    config = {}

    opts = results.get('optimizations', {})

    # Plinko
    if 'plinko_temperature' in opts:
        params = opts['plinko_temperature']['best_parameters']
        config['plinko'] = {
            'initialTemperature': params.get('initial_temp', 2.5),
            'schedule': params.get('schedule_type', 'exponential'),
            'decayRate': params.get('decay_rate', 0.995),
            'minTemperature': params.get('min_temp', 0.1)
        }

    # TD(λ)
    if 'td_lambda_optimization' in opts:
        params = opts['td_lambda_optimization']['best_parameters']
        config['tdLambda'] = {
            'lambda': params.get('lambda', 0.95),
            'alpha': params.get('alpha', 0.1),
            'gamma': params.get('gamma', 0.99)
        }

    # VAE
    if 'vae_architecture' in opts:
        params = opts['vae_architecture']['best_parameters']
        config['vae'] = {
            'latentDim': params.get('latent_dim', 128),
            'beta': params.get('beta', 1.0),
            'capacity': params.get('capacity', None)
        }

    # Graph evolution
    if 'graph_evolution_params' in opts:
        params = opts['graph_evolution_params']['best_parameters']
        config['evolution'] = {
            'pruningThreshold': params.get('pruning_threshold', 0.3),
            'graftingRate': params.get('grafting_rate', 0.1),
            'clusteringResolution': params.get('clustering_resolution', 1.0)
        }

    # META
    if 'meta_differentiation' in opts:
        params = opts['meta_differentiation']['best_parameters']
        config['meta'] = {
            'signalResponseRate': params.get('signal_response_rate', 0.1),
            'differentiationThreshold': params.get('differentiation_threshold', 0.9),
            'plasticityRule': params.get('plasticity_rule', 'oja')
        }

    return config


def main():
    """Main execution"""

    # Get script directory
    script_dir = Path(__file__).parent

    # Load unified config
    results_path = script_dir / 'results' / 'unified_config.json'

    if not results_path.exists():
        print(f"Error: {results_path} not found.")
        print("Run 'python run_all.py' first to generate optimization results.")
        return

    with open(results_path, 'r') as f:
        results = json.load(f)

    # Generate TypeScript config
    ts_content = generate_typescript_config(results)

    # Get output path
    # Navigate to project root and then to src/core/config
    project_root = script_dir.parent.parent.parent  # simulations/optimization/hyperparams -> polln
    output_dir = project_root / 'src' / 'core' / 'config'
    output_dir.mkdir(parents=True, exist_ok=True)

    ts_output_path = output_dir / 'optimized.ts'

    # Write TypeScript file
    with open(ts_output_path, 'w') as f:
        f.write(ts_content)

    print(f"✓ Generated TypeScript config: {ts_output_path.relative_to(project_root)}")

    # Generate JSON config
    json_config = generate_json_config(results)
    json_output_path = output_dir / 'optimized.json'

    with open(json_output_path, 'w') as f:
        json.dump(json_config, f, indent=2)

    print(f"✓ Generated JSON config: {json_output_path.relative_to(project_root)}")

    print("\nConfiguration files generated successfully!")
    print("\nUsage in TypeScript:")
    print("```typescript")
    print("import { OPTIMIZED_CONFIG } from './config/optimized';")
    print("")
    print("const temperature = OPTIMIZED_CONFIG.plinko.initialTemperature;")
    print("const lambda = OPTIMIZED_CONFIG.tdLambda.lambda;")
    print("```")


if __name__ == '__main__':
    main()
