// Auto-generated by simulations/optimization/hyperparams/
// DO NOT EDIT MANUALLY - Regenerate with: python simulations/optimization/hyperparams/run_all.py

/**
 * Optimized hyperparameters for POLLN components.
 *
 * These values were found through Bayesian optimization and grid search
 * to maximize performance, convergence speed, and stability.
 *
 * @module config/optimized
 */

// Note: These are default placeholder values.
// Run the optimization framework to generate optimized values:
//   cd simulations/optimization/hyperparams
//   python run_all.py

/** Plinko temperature schedule parameters */
export const PLINKO_CONFIG = {
  /** Initial temperature for exploration */
  initialTemperature: 2.5,
  /** Temperature schedule type */
  schedule: 'exponential',
  /** Decay rate for temperature annealing */
  decayRate: 0.995,
  /** Minimum temperature floor */
  minTemperature: 0.1
} as const;

/** TD(λ) reinforcement learning parameters */
export const TD_LAMBDA_CONFIG = {
  /** Eligibility trace decay [0, 1] */
  lambda: 0.95,
  /** Learning rate [0, 1] */
  alpha: 0.1,
  /** Discount factor [0, 1] */
  gamma: 0.99
} as const;

/** VAE world model architecture parameters */
export const VAE_CONFIG = {
  /** Latent dimension size */
  latentDim: 128,
  /** β-VAE parameter (KL divergence weight) */
  beta: 1.0,
  /** Capacity limit for KL divergence (null = no limit) */
  capacity: 10
} as const;

/** Graph evolution parameters */
export const GRAPH_EVOLUTION_CONFIG = {
  /** Threshold for pruning weak connections */
  pruningThreshold: 0.3,
  /** Rate for grafting new connections */
  graftingRate: 0.1,
  /** Resolution for community detection */
  clusteringResolution: 1.0
} as const;

/** META tile differentiation parameters */
export const META_CONFIG = {
  /** Rate of response to signals */
  signalResponseRate: 0.1,
  /** Threshold for differentiation */
  differentiationThreshold: 0.9,
  /** Plasticity rule for weight updates */
  plasticityRule: 'oja'
} as const;

/** Unified configuration object */
export const OPTIMIZED_CONFIG = {
  plinko: PLINKO_CONFIG,
  tdLambda: TD_LAMBDA_CONFIG,
  vae: VAE_CONFIG,
  evolution: GRAPH_EVOLUTION_CONFIG,
  meta: META_CONFIG
} as const;

// Type definitions
export type PlinkoConfig = typeof PLINKO_CONFIG;
export type TDLambdaConfig = typeof TD_LAMBDA_CONFIG;
export type VAEConfig = typeof VAE_CONFIG;
export type GraphEvolutionConfig = typeof GRAPH_EVOLUTION_CONFIG;
export type MetaConfig = typeof META_CONFIG;
export type OptimizedConfig = typeof OPTIMIZED_CONFIG;
