/**
 * Multi-modal Domain for POLLN
 *
 * This file exports the multi-modal configuration and utilities.
 * Note: The actual config.ts file will be generated by running the simulations.
 *
 * To generate the configuration:
 * 1. cd simulations/domains/multimodal
 * 2. python run_all.py
 */

// Re-export from generated config
export { MULTIMODAL_DOMAIN_CONFIG } from './config';

// Re-export types
export type Modality = 'text' | 'image' | 'audio' | 'code';
export type FusionStrategy = 'early' | 'late' | 'hierarchical' | 'co_attention' | 'transformer_fusion';
export type ArchitectureType = 'unified' | 'separate' | 'mixture_of_experts';

// Re-export helper functions if config is generated
try {
  const configModule = require('./config');
  if (configModule.getOptimalAgentConfig) {
    exports.getOptimalAgentConfig = configModule.getOptimalAgentConfig;
  }
  if (configModule.getOptimalFusionStrategy) {
    exports.getOptimalFusionStrategy = configModule.getOptimalFusionStrategy;
  }
  if (configModule.getGenerationParams) {
    exports.getGenerationParams = configModule.getGenerationParams;
  }
} catch (e) {
  // Config not yet generated, that's okay
  console.warn('Multi-modal config not yet generated. Run simulations first.');
}
