/**
 * Auto-generated topology templates for POLLN
 * Generated by topology optimization simulations
 * DO NOT EDIT MANUALLY
 */

import { TopologyTemplate, TopologyParams } from './types';

/**
 * Topology templates for different colony sizes and workloads
 */
export const TOPOLOGY_TEMPLATES: Record<string, TopologyTemplate> = {
  SMALL_COLONY: {
    name: 'Small Colony',
    description: 'Optimal for colonies of 1-20 agents. High efficiency, low cost.',
    colonySizeRange: [1, 20],
    topologyType: 'watts_strogatz',
    params: {
      "k": 4,
      "p": 0.1
    },
    expectedMetrics: {
      "avgPathLength": 2.5,
      "clusteringCoeff": 0.4,
      "globalEfficiency": 0.7,
      "localEfficiency": 0.6,
      "attackTolerance": 0.7,
      "failureTolerance": 0.8,
      "edgeCost": 0.15,
      "degreeCost": 0.2
    },
    characteristics: {
      "network_type": "small_world",
      "efficiency": "high",
      "robustness": "medium",
      "cost": "low"
    },
    useCases: [
      "Small teams",
      "Prototype colonies",
      "Local clusters"
    ],
    limitations: [
      "Not suitable for large-scale deployments"
    ]
  },

  MEDIUM_COLONY: {
    name: 'Medium Colony',
    description: 'Optimal for colonies of 21-100 agents. Balanced efficiency and robustness.',
    colonySizeRange: [21, 100],
    topologyType: 'watts_strogatz',
    params: {
      "k": 6,
      "p": 0.2
    },
    expectedMetrics: {
      "avgPathLength": 3.2,
      "clusteringCoeff": 0.35,
      "globalEfficiency": 0.65,
      "localEfficiency": 0.55,
      "attackTolerance": 0.65,
      "failureTolerance": 0.75,
      "edgeCost": 0.2,
      "degreeCost": 0.25
    },
    characteristics: {
      "network_type": "small_world",
      "efficiency": "medium",
      "robustness": "medium",
      "cost": "medium"
    },
    useCases: [
      "Medium-scale deployments",
      "Production systems",
      "Multi-team coordination"
    ],
    limitations: [
      "May need optimization for specialized workloads"
    ]
  },

  LARGE_COLONY: {
    name: 'Large Colony',
    description: 'Optimal for colonies of 101-500 agents. Hierarchical with high robustness.',
    colonySizeRange: [101, 500],
    topologyType: 'hierarchical',
    params: {
      "levels": 3,
      "k": 6
    },
    expectedMetrics: {
      "avgPathLength": 4.5,
      "clusteringCoeff": 0.3,
      "globalEfficiency": 0.55,
      "localEfficiency": 0.5,
      "attackTolerance": 0.8,
      "failureTolerance": 0.85,
      "edgeCost": 0.15,
      "degreeCost": 0.3
    },
    characteristics: {
      "network_type": "community",
      "efficiency": "medium",
      "robustness": "high",
      "cost": "medium"
    },
    useCases: [
      "Large-scale deployments",
      "Enterprise systems",
      "Distributed coordination"
    ],
    limitations: [
      "Higher latency due to hierarchy"
    ]
  },

  VERY_LARGE_COLONY: {
    name: 'Very Large Colony',
    description: 'Optimal for colonies of 501-1000+ agents. Modular with extreme robustness.',
    colonySizeRange: [501, 10000],
    topologyType: 'modular',
    params: {
      "modules": 10,
      "k": 6
    },
    expectedMetrics: {
      "avgPathLength": 5.5,
      "clusteringCoeff": 0.4,
      "globalEfficiency": 0.5,
      "localEfficiency": 0.6,
      "attackTolerance": 0.85,
      "failureTolerance": 0.9,
      "edgeCost": 0.12,
      "degreeCost": 0.2
    },
    characteristics: {
      "network_type": "community",
      "efficiency": "medium",
      "robustness": "high",
      "cost": "low"
    },
    useCases: [
      "Massive deployments",
      "Cloud-scale systems",
      "Global coordination"
    ],
    limitations: [
      "Complex setup and configuration"
    ]
  },

  HIGH_EFFICIENCY: {
    name: 'High Efficiency',
    description: 'Maximum efficiency at higher cost. For latency-sensitive applications.',
    colonySizeRange: [1, 100],
    topologyType: 'two_tier',
    params: {
      "k": 8
    },
    expectedMetrics: {
      "avgPathLength": 2.0,
      "clusteringCoeff": 0.25,
      "globalEfficiency": 0.8,
      "localEfficiency": 0.5,
      "attackTolerance": 0.5,
      "failureTolerance": 0.6,
      "edgeCost": 0.35,
      "degreeCost": 0.5
    },
    characteristics: {
      "network_type": "small_world",
      "efficiency": "high",
      "robustness": "low",
      "cost": "high"
    },
    useCases: [
      "Real-time systems",
      "High-frequency trading",
      "Low-latency applications"
    ],
    limitations: [
      "Higher cost",
      "Lower robustness"
    ]
  },

  HIGH_ROBUSTNESS: {
    name: 'High Robustness',
    description: 'Maximum robustness and fault tolerance. For critical systems.',
    colonySizeRange: [50, 1000],
    topologyType: 'modular',
    params: {
      "modules": 7,
      "k": 6
    },
    expectedMetrics: {
      "avgPathLength": 4.8,
      "clusteringCoeff": 0.45,
      "globalEfficiency": 0.52,
      "localEfficiency": 0.65,
      "attackTolerance": 0.9,
      "failureTolerance": 0.95,
      "edgeCost": 0.18,
      "degreeCost": 0.25
    },
    characteristics: {
      "network_type": "community",
      "efficiency": "medium",
      "robustness": "high",
      "cost": "medium"
    },
    useCases: [
      "Mission-critical systems",
      "Fault-tolerant deployments",
      "High-availability"
    ],
    limitations: [
      "Higher latency",
      "Moderate cost"
    ]
  },

  LOW_COST: {
    name: 'Low Cost',
    description: 'Minimum edge count. For resource-constrained environments.',
    colonySizeRange: [1, 200],
    topologyType: 'erdos_renyi',
    params: {
      "p": 0.05
    },
    expectedMetrics: {
      "avgPathLength": 3.8,
      "clusteringCoeff": 0.05,
      "globalEfficiency": 0.55,
      "localEfficiency": 0.4,
      "attackTolerance": 0.5,
      "failureTolerance": 0.6,
      "edgeCost": 0.05,
      "degreeCost": 0.1
    },
    characteristics: {
      "network_type": "random",
      "efficiency": "medium",
      "robustness": "low",
      "cost": "low"
    },
    useCases: [
      "Resource-constrained",
      "Edge computing",
      "IoT deployments"
    ],
    limitations: [
      "Lower robustness",
      "Poor clustering for learning"
    ]
  }
};

/**
 * Get recommended template for colony size
 */
export function getTemplateForSize(size: number): TopologyTemplate | null {
  const matchingTemplates = Object.values(TOPOLOGY_TEMPLATES).filter(
    t => size >= t.colonySizeRange[0] && size <= t.colonySizeRange[1]
  );

  if (matchingTemplates.length === 0) return null;

  // Return first match (could be refined with more sophisticated logic)
  return matchingTemplates[0];
}

/**
 * Get all templates for a size range
 */
export function getTemplatesInRange(min: number, max: number): TopologyTemplate[] {
  return Object.values(TOPOLOGY_TEMPLATES).filter(
    t => t.colonySizeRange[1] >= min && t.colonySizeRange[0] <= max
  );
}
