#!/bin/bash
set -e

# POLLN Production Build Script
# Optimized build with TypeScript compilation and bundle optimization

echo "🔨 POLLN Production Build Script"
echo "================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Parse arguments
CLEAN=false
WATCH=false
ANALYZE=false
SOURCE_MAP=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --clean)
      CLEAN=true
      shift
      ;;
    --watch)
      WATCH=true
      shift
      ;;
    --analyze)
      ANALYZE=true
      shift
      ;;
    --source-map)
      SOURCE_MAP=true
      shift
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

echo "📋 Build Configuration:"
echo "  Clean: $CLEAN"
echo "  Watch: $WATCH"
echo "  Analyze: $ANALYZE"
echo "  Source Maps: $SOURCE_MAP"
echo ""

# Clean build directory
if [ "$CLEAN" = true ]; then
  echo "🧹 Cleaning build directory..."
  rm -rf dist/
  rm -rf .rollup.cache/
  rm -rf tsconfig.tsbuildinfo
  echo -e "${GREEN}✓ Clean complete${NC}\n"
fi

# Install dependencies
echo "📦 Installing dependencies..."
npm ci
echo -e "${GREEN}✓ Dependencies installed${NC}\n"

# TypeScript compilation
echo "🔷 Compiling TypeScript..."
if [ "$WATCH" = true ]; then
  npx tsc --watch &
  TSC_PID=$!
else
  npx tsc
fi
echo -e "${GREEN}✓ TypeScript compilation complete${NC}\n"

# Build production bundle
echo "📦 Building production bundle..."
BUILD_ARGS=""

if [ "$SOURCE_MAP" = true ]; then
  BUILD_ARGS="$BUILD_ARGS --source-map"
fi

if [ "$ANALYZE" = true ]; then
  BUILD_ARGS="$BUILD_ARGS --analyze"
fi

npm run build:production -- $BUILD_ARGS
echo -e "${GREEN}✓ Production bundle built${NC}\n"

# Optimize bundle size
echo "⚡ Optimizing bundle size..."

# Minify CSS
find dist/ -name "*.css" -exec cssnano {} {} \;

# Compress assets
find dist/ -name "*.js" -exec gzip -k {} \;
find dist/ -name "*.css" -exec gzip -k {} \;
find dist/ -name "*.json" -exec gzip -k {} \;

echo -e "${GREEN}✓ Bundle optimization complete${NC}\n"

# Generate asset manifest
echo "📝 Generating asset manifest..."
node -e "
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

function getHash(filePath) {
  const content = fs.readFileSync(filePath);
  return crypto.createHash('sha256').update(content).digest('hex').substring(0, 16);
}

function walkDir(dir, callback) {
  const files = fs.readdirSync(dir);
  files.forEach(file => {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    if (stat.isDirectory()) {
      walkDir(filePath, callback);
    } else {
      callback(filePath);
    }
  });
}

const manifest = {};
walkDir('dist/', (filePath) => {
  if (fs.statSync(filePath).isFile()) {
    const relativePath = path.relative('dist/', filePath);
    const hash = getHash(filePath);
    manifest[relativePath] = {
      hash,
      size: fs.statSync(filePath).size
    };
  }
});

fs.writeFileSync('dist/asset-manifest.json', JSON.stringify(manifest, null, 2));
"
echo -e "${GREEN}✓ Asset manifest generated${NC}\n"

# Check bundle size
echo "📊 Bundle size analysis:"
BUNDLE_SIZE=$(du -sh dist/ | cut -f1)
echo "  Total: $BUNDLE_SIZE"

# Find largest files
echo ""
echo "📁 Largest files:"
du -sh dist/* | sort -rh | head -10

# Size limits
MAX_SIZE=50M
ACTUAL_SIZE=$(du -sm dist/ | cut -f1)
if [ "$ACTUAL_SIZE" -gt "$MAX_SIZE" ]; then
  echo -e "${RED}❌ Bundle size exceeds ${MAX_SIZE}M limit${NC}"
  exit 1
fi

echo -e "${GREEN}✓ Bundle size within ${MAX_SIZE}M limit${NC}\n"

# Generate source maps
if [ "$SOURCE_MAP" = true ]; then
  echo "🗺️  Generating source maps..."
  # Source maps are already generated by TypeScript and bundler
  echo -e "${GREEN}✓ Source maps generated${NC}\n"
fi

# Bundle analysis
if [ "$ANALYZE" = true ]; then
  echo "📈 Analyzing bundle composition..."
  npm run analyze
  echo ""
fi

# Run type check
echo "🔍 Running type check..."
npx tsc --noEmit
echo -e "${GREEN}✓ Type check passed${NC}\n"

# Run linter
echo "🔍 Running linter..."
npm run lint
echo -e "${GREEN}✓ Linter passed${NC}\n"

# Generate build info
echo "📝 Generating build info..."
cat > dist/build-info.json << EOF
{
  "version": "$(node -p "require('./package.json').version")",
  "buildTime": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "gitCommit": "$(git rev-parse HEAD)",
  "gitBranch": "$(git rev-parse --abbrev-ref HEAD)",
  "nodeVersion": "$(node --version)",
  "npmVersion": "$(npm --version)"
}
EOF
echo -e "${GREEN}✓ Build info generated${NC}\n"

# Cleanup
if [ "$WATCH" = false ]; then
  echo "🧹 Cleaning up..."
  rm -f dist/**/*.test.ts
  rm -f dist/**/*.spec.ts
  rm -f dist/**/*.mock.ts
  echo -e "${GREEN}✓ Cleanup complete${NC}\n"
fi

# Summary
echo "================================="
echo -e "${GREEN}✅ Build complete!${NC}"
echo ""
echo "Build artifacts:"
echo "  dist/          - Compiled JavaScript"
echo "  dist/build-info.json - Build metadata"
echo "  dist/asset-manifest.json - Asset hashes"
echo ""
echo "Next steps:"
echo "  npm run test:smoke    - Run smoke tests"
echo "  npm run deploy:staging - Deploy to staging"
echo ""

# Keep watching if requested
if [ "$WATCH" = true ]; then
  echo "👀 Watching for changes..."
  wait $TSC_PID
fi
